title: <p align="center"> Mahesh Kankar </p>
logo: /assets/img/WhatsApp Image 2023-01-01 at 11.33.38 AM.jpeg

description:
  <p align="center">
  <a href="pdf/Mahesh_Kankar_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mahesh-kankar-7aa5a4116/">LinkedIn</a> |
  <a href="https://github.com/maheshkankar">GitHub</a>
 
  <br>  
  I am working on processing, analysing data, Bulding, deploying ML models and making automation pipeline on AWS for ML models on huge data and Making business decision by getting actionable insights in healthcare.
  <br>
  </p>

theme: jekyll-theme-minimal
