title: <p align="center"> Mahesh Kankar </p>
logo: /assets/img/WhatsApp Image 2023-01-01 at 11.33.38 AM.jpeg

description:
  <p align="center">
  <a href="pdf/Mahesh_Kankar_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mahesh-kankar-7aa5a4116/">LinkedIn</a> |
  <a href="https://github.com/maheshkankar">GitHub</a>
 
  <br>  
  I am working as a Software Engineer professional having a track record of processing and analysing data, Bulding, deploying making automation pipeline on AWS for ML models on huge amount of data. Tech modernization using spark Scala.
  Making business decision by getting actionable insights in heathcare.
  <br>
  </p>

theme: jekyll-theme-minimal
